from Button_pogoda.button_1 import key_start
from Button_pogoda.button_region import key_region
from Button_pogoda.button_time import key_time
from Button_pogoda.button_region import key_today
from Button_pogoda.button_1 import key_back_yandex_1
from Button_pogoda.button_region import key_bigmur
from Button_pogoda.button_time import key_mur
from Button_pogoda.button_time import back_mur
from Button_pogoda.button_time import perv
from Button_pogoda.button_time import back_per
from Button_pogoda.button_time import arzb
from Button_pogoda.button_time import back_arz
from Button_pogoda.button_time import butb
from Button_pogoda.button_time import back_but
from Button_pogoda.button_time import butkonya
from Button_pogoda.button_time import back_konya
from Button_pogoda.button_time import butnino
from Button_pogoda.button_time import back_nino
from Button_pogoda.button_bor import butbor
from Button_pogoda.button_bor import back_bor
from Button_pogoda.button_time import butbor
from Button_pogoda.button_time import back_bor